# Generated by Django 5.0.1 on 2024-08-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_code', models.CharField(blank=True, max_length=10, null=True)),
                ('factory_name', models.CharField(max_length=256)),
            ],
        ),
    ]
