# Generated by Django 5.1 on 2024-08-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='factory_name',
            field=models.CharField(max_length=256, verbose_name='Tên nhà máy'),
        ),
    ]
