# Generated by Django 5.0.1 on 2024-08-10 03:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=32, verbose_name='Họ và tên')),
                ('truck_number', models.CharField(max_length=32, verbose_name='Số xe/số container')),
                ('phone_number', models.CharField(max_length=32, verbose_name='Số điện thoại')),
                ('checkin_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Giờ check-in')),
                ('shipper', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chủ hàng')),
                ('remark', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Ghi chú')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factory.factory')),
            ],
        ),
    ]
