# Generated by Django 5.1 on 2024-08-13 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
        ('factory', '0002_alter_factory_factory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factory.factory'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='shipper',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipper'),
        ),
    ]
