# Generated by Django 5.0.1 on 2024-08-15 06:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_alter_checkin_factory_alter_checkin_shipper'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signature/'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='checkin_time',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Giờ check-in'),
        ),
    ]
