# Generated by Django 5.1 on 2024-08-16 04:13

import jsignature.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_checkin_signature_image_alter_checkin_checkin_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='signature_image',
        ),
        migrations.AddField(
            model_name='checkin',
            name='signature',
            field=jsignature.fields.JSignatureField(blank=True, null=True),
        ),
    ]
