# Generated by Django 5.1 on 2024-08-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_remove_checkin_signature_image_checkin_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
